spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: root
    password: 1234
    driver-class-name: org.h2.Driver

  jap:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace